### ISSUE TITLE
Dropout not set

### ISSUE THREAD

**Issue by TJKlein** [layer6ai-labs/TabDPT#4]
The dropout argument is never used:
https://github.com/layer6ai-labs/TabDPT/blob/713686b7b3817671edc73caa8f76d46ae98d3c7f/tabdpt_model.py#L14

I suppose the 0.0 default value should be should be replaced with **dropout** from the constructor arguments, which seems to be non-zero (0.1):
```python
TransformerEncoderLayer(activation="gelu", d_model=ninp, dim_feedforward=nhid, dropout=dropout, nhead=nhead, norm_first=norm_first)
```
Let me know, if I should create a PR.

**Comment by junweima** [comment]
Thanks for the catch! I've updated it as per your suggestion. 
But just to affirm, we don't use dropout in the models we published.

**Comment by TJKlein** [comment]
But if I remember correctly, the configuration from the checkpoint states **dropout=0.1**.

**Comment by junweima** [comment]
@TJKlein It appears that it is a typo. We do not use dropout for evaluation or for training.
